BIN = SuperJohannes
CC = g++
FLAGS = -Wall -pedantic -mmacosx-version-min=10.5 -arch x86_64 -fmessage-length=0 -UGLFW_CDECL -fprofile-arcs -ftest-coverage
INC = -I external/include -I/sw/include -I/usr/local/include
LOC_LIB = external/lib/osx_64/libGLEW.a external/lib/osx_64/libglfw3.a
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = $(wildcard src/*.cpp)

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB}
